### PR TITLE
Some basic improvements (app-cache, content-type: text/html, publish event clear)

### PR DESCRIPTION
**Pull request by ecsplendid**
Hey Kevin!

No obligation to accept this PR but thought I would make it in case you were interested in taking down the changes. 

Also note that you can may now call any page with ?no-cache and it will bypass and re-generate the cache for that page. 

Warm regards

Tim

### CODE REVIEW

**Comment by kgiszewski** [comment]
Wow, this is quite the update. Thank you.

It may be better in the end for you to take this project over. Did you release an Umbraco package based on this yet?

**Comment by ecsplendid** [comment]
I did yes, just hosted on my Google Drive -- https://drive.google.com/a/developer-x.com/file/d/0Bz9S4LIuPplkSkl4dHVkVTV4Nnc/view?usp=sharing

Happy to take it over or perhaps just put a pointer to my fork?

Note that there is one potential bug left to fix (on yours and mine) where it might try and write to the file system while another thread is reading from it at the same time (see addendum for stack trace). Will fix this later today. 

Best,

Tim

---

Exception information:
Exception type: IOException
Exception message: The process cannot access the file 'D:\home\site\wwwroot\FastCache\c5ea19c6c1d8d54d9044284c2b130690.html' because it is being used by another process. at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath) at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost) at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost) at System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost) at System.IO.File.WriteAllText(String path, String contents) at FastCache.CacheModule.Finish(Object sender, EventArgs e) at System.Web.HttpApplication.SendResponseExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

**Comment by kgiszewski** [comment]
Honestly, I think you've done so much work that I'd be inclined to just reference your fork on GitHub and put a comment on my Our Umbraco that refers to your newer version.

I haven't used my own package since v6 and I think you're more fit to continue it :+1:

**Review by kgiszewski — COMMENTED** [review]
Thanks for the PR but this project is long since dead. If you still use it I would suggest forking and maintaining the releases (and release on Our/Nuget). I will add a note that this project is no longer active.

**Pull request closed without merging**
